### ISSUE TITLE
invalid syntax line 20 in core

### ISSUE THREAD

**Issue by smithan7** [sparkfun/Qwiic_Ublox_Gps_Py#17]
When trying to run the dexamples I get the following error:
*********************
Qwiic_Ublox_Gps_Py/examples$ python dead_reckoning_ex3.py 
Traceback (most recent call last):
  File "dead_reckoning_ex3.py", line 38, in <module>
    from ublox_gps import UbloxGps
  File "/usr/local/lib/python2.7/dist-packages/ublox_gps/__init__.py", line 58, in <module>
    from .ublox_gps import UbloxGps
  File "/usr/local/lib/python2.7/dist-packages/ublox_gps/ublox_gps.py", line 54, in <module>
    from . import sparkfun_predefines as sp
  File "/usr/local/lib/python2.7/dist-packages/ublox_gps/sparkfun_predefines.py", line 3, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/ublox_gps/core.py", line 20
    def __init__(self, repeat: int = 0):
                             ^
SyntaxError: invalid syntax

***************
Any help you can provide would be appreciated!

**Comment by edspark** [comment]
It looks like you're using Python 2.7, this library only supports 3.5 and above.
