### ISSUE TITLE
Jetson Nano Trackback error importing UbloxGps and spidev - Python 3

### ISSUE THREAD

**Issue by SPflaum** [sparkfun/Qwiic_Ublox_Gps_Py#21]
Hi everybody,
just installed according to the procedure on Jetson Nano.
Launching test_script.py (from folder in home-folder) produces the following error message.
I appreciate your advice.
Thanks, 
Sebastian

jetson2@jetson2-desktop:~/UBLOX_M9N_GPS$ python3 test_script.py
Traceback (most recent call last):
  File "test_script.py", line 10, in <module>
    from ublox_gps import UbloxGps
  File "/usr/local/lib/python3.6/dist-packages/ublox_gps/__init__.py", line 58, in <module>
    from .ublox_gps import UbloxGps
  File "/usr/local/lib/python3.6/dist-packages/ublox_gps/ublox_gps.py", line 48, in <module>
    import spidev
ModuleNotFoundError: No module named 'spidev'

**Comment by niranjanravilevelup** [comment]
Hi,
    Are you trying to connect using a USB port or an UART?
